export const ERROR_CODES = {
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_INVALID_AUDIENCE: "AUTH_INVALID_AUDIENCE",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_NOT_READY: "WALLET_NOT_READY",
  WALLET_PROVISIONING_TIMEOUT: "WALLET_PROVISIONING_TIMEOUT",
  IKA_TRANSIENT_NETWORK_ERROR: "IKA_TRANSIENT_NETWORK_ERROR",
  IKA_UNSUPPORTED_MODE: "IKA_UNSUPPORTED_MODE",
  SPONSOR_BALANCE_LOW: "SPONSOR_BALANCE_LOW",
  REQUEST_RATE_LIMITED: "REQUEST_RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
